using System;
using System.Collections.Generic;

namespace SmartJobRecommender.Models.ViewModels
{
    // ViewModel used to present a personalized overview to the logged-in user
    public class DashboardViewModel
    {
        public string UserName { get; set; } // User's email or username
        public int TotalSkills { get; set; }
        public DateTime? LastAnalyzed { get; set; } // When the resume was last analyzed

        // List of the user's current skills
        public List<string> UserSkills { get; set; } = new List<string>();

        // List of top job recommendations generated by the service
        public List<RecommendedJobViewModel> TopRecommendations { get; set; } = new List<RecommendedJobViewModel>();

        // List of the most critical missing skills identified across top jobs
        public List<string> CriticalMissingSkills { get; set; } = new List<string>();
    }
}